version: 0.0
os: linux
files: 
  - source: /
    destination: /home/ubuntu/blogprojectdrf

permissions:
  - object: /home/ubuntu/blogprojectdrf
    owner: ubuntu
    group: ubuntu

hooks:
  BeforeInstall:
    # Clean up the instance, remove any existing files
    - location: scripts/clean_instance.sh
      timeout: 300
      runas: ubuntu
    # New script to remove existing files before deploying
    - location: scripts/remove_existing_files.sh
      timeout: 300
      runas: ubuntu

  AfterInstall:
    - location: scripts/instance_os_dependencies.sh
      timeout: 300
      runas: ubuntu
    - location: scripts/python_dependencies.sh
      timeout: 300
      runas: ubuntu
    - location: scripts/gunicorn.sh
      timeout: 300
      runas: ubuntu
    - location: scripts/nginx.sh
      timeout: 300
      runas: ubuntu

  ApplicationStop:
    - location: scripts/stop_app.sh
      timeout: 300
      runas: ubuntu

  ApplicationStart:
    - location: scripts/start_app.sh
      timeout: 300
      runas: ubuntu
